export const NEW_EVENT = "NEW_EVENT";
export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";


export const EVENT_REQUEST_ERROR = "AUTH_REQUEST_ERROR";
export const CLEAR_ERROR = "CLEAR_AUTH_ERROR";

export const TOGGLE_PROCESSING = "TOGGLE_AUTH_PROCESSING";